pipeline:
  build:
    image: node:14.9.0
    commands:
      - yarn
      - yarn build

  deploy:
    image: node:14.9.0
    commands:
      - yarn deploy
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    when:
      branch: main
