version: '2'
services:
  keycloak:
    build: ./docker
    ports:
    - "8080:8080"
    volumes:
    - ./dist/theme/csh:/opt/jboss/keycloak/themes/csh
    environment:
    - PROXY_ADDRESS_FORWARDING=true
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=admin
