<#import "template.ftl" as layout>
<@layout.registrationLayout; section>
    <#if section = "title">
    ${msg("loginTitle",realm.displayName)}
    <#elseif section = "header">
    ${msg("loginTitleHtml",realm.displayNameHtml)}
    <#elseif section = "form">
    <form id="kc-totp-login-form" action="${url.loginAction}" method="post">
        <div class="row">
            <div class="col-sm-2 col-xs-12 otp-icon">
                <img src="${url.resourcesPath}/img/otp.svg" alt="One-time code"/>
            </div>
            <div class="col-sm-10 col-xs-12">
                <div class="form-group">
                    <label for="totp" class="control-label">Enter the one-time code generated by your mobile application.</label>
                    <input id="totp" name="totp" autocomplete="off" type="text" class="form-control" autofocus />
                </div>

                <div class="login-actions">
                    <div class="login-actions-left">
                        <input class="btn btn-link" name="cancel" type="submit" value="${msg("doCancel")}"/>
                    </div>
                    <div class="login-actions-right">
                        <input class="btn btn-primary btn-lg" name="login" type="submit" value="${msg("verify")}"/>
                    </div>
                </div>
            </div>
        </div>
    </form>
    </#if>
</@layout.registrationLayout>